### PR TITLE
Testing highfive setup

### PR DESCRIPTION
**Pull request by manaskarekar**
Reject this pr.

r? @fitzgen or others

Thanks!

### CODE REVIEW

**Comment by manaskarekar** [comment]
Looks like that didn't work.

**Comment by fitzgen** [comment]
@manaskarekar thanks for digging into this highfive stuff!

**Comment by manaskarekar** [comment]
@fitzgen I believe I ran into this earlier and if I understand right, these would need to be done by someone with write access to the repo:  https://github.com/servo/highfive#enabling-a-repo

Just to be sure, we're using rust-highfive and not the servo/highfive, right?

**Comment by manaskarekar** [comment]
@fitzgen I believe I ran into this earlier and if I understand right, this would need to be done by someone with write access to the repo: https://github.com/rust-lang-nursery/highfive#enabling-a-repo

Setting up the webhook: https://github.com/servo/servo/wiki/Highfive#setting-up-highfive-on-new-repositories

Just to be sure, we're using rust-lang-nursery/highfive and not the servo/highfive, right?

**Comment by fitzgen** [comment]
> Just to be sure, we're using rust-lang-nursery/highfive and not the servo/highfive, right?

yeah

**Comment by fitzgen** [comment]
Ok I added the webhook, pointing to http://www.joshmatthews.net/highfive/newpr.py; is that the right one?

**Comment by fitzgen** [comment]
Perhaps @alexcrichton knows which highfive URL we should be posting to.

**Comment by alexcrichton** [comment]
I switched to https and it looks like it may be working now?

**Comment by manaskarekar** [comment]
Issue resolved as per: https://github.com/rust-lang-nursery/rust-wasm/pull/74#issuecomment-370038686

**Pull request closed without merging**
